version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  publish_to_chromatic:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Publish to Chromatic
          command: |
            yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN

workflows:
  version: 2
  publish_to_chromatic:
    jobs:
      - publish_to_chromatic