version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  publish_to_chromatic:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Publish to Chromatic
          command: |
            yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN

workflows:
  version: 2
  publish_to_chromatic:
    jobs:
      - publish_to_chromatic