version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.18-buster

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            yarn install

      - run:
          name: Run Chromatic
          command: |
            yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
            